version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - pegjs
  - Rezza
  - vuadu
ignoreWords: []
import: []
ignoreRegExpList:
  - >-
    /"/[^"]+"/
  - >-
    /vie": "[^"]+"/
